
export const LOAD_ERROR = 'LOAD_ERROR'
export const POST_ERROR = 'POST_ERROR'

export const LOADING_POST = 'LOADING_POST';
export const LOADING_CATEGORY = 'LOADING_CATEGORY'

export const RECEIVED_CATEGORIES = 'RECEIVED_CATEGORIES'
export const UPLOAD_SUCCESS = 'UPLOAD_SUCCESS'